#!/bin/bash

#select opts in coplite

#do

#complete -W 'eu-tlp.sbtech.info us-tlp.sbtech.info' host
#complete -W 'eu-tlp.sbtech.info us-tlp.sbtech.info' dig
#1)complete -W '-eu -us -cl -kls -kl -ns -nl -l -jae -jau -cpe -cpu -s -lo -h' jj
#2)complete -W '$(cat eunodes)' jj -l
#3)complete -W '$(cat usnodes)' jj -l
case $1 in

-eu)
 complete -W '-eu -us -cl -kls -kl -ns -nl -l -jae -jau -cpe -cpu -s -lo -h' jj
 complete -W '$(cat /mnt/c/Users/georgi.dimi/Downloads/scripts/eunodes)' jj -ns
 complete -W '$(cat /mnt/c/Users/georgi.dimi/Downloads/scripts/eunodes)' jj -l ;;
-us)
 complete -W '-eu -us -cl -kls -kl -ns -nl -l -jae -jau -cpe -cpu -s -lo -h' jj
 complete -W '$(cat /mnt/c/Users/georgi.dimi/Downloads/scripts/usnodes)' jj -ns
 complete -W '$(cat /mnt/c/Users/georgi.dimi/Downloads/scripts/usnodes)' jj -l ;;
*)
 echo "posible options is -eu or -us" ;;
esac
